#########################################################################################################
#----------------------------------------vCardGenerator_v1.0--------------------------------------------#
#-------------------------------------------------------------------------------------------------------#
#---Overview:-------Script generates fake vCards of 3.0 version with or without photo-------------------#
#-------------------------------------------------------------------------------------------------------#
#---Instruction:----Script is able to receive 2 arguments:----------------------------------------------#
#-------------------	- quantityParametr (int) - quantity of generated contacts; default value = 10---#
#-------------------	- isPhotoParametr (bool) - option for photo adding; default value = False-------#
#-------------------Arguments can be given in any order, independently from each other------------------#
#-------------------If no arguments will be given - assumed generating of 10 contacts w/o photo---------#
#-------------------------------------------------------------------------------------------------------#
#---Developer:------Maksym Melanchenko------------------------------------------------------------------#
#-------------------------------------------------------------------------------------------------------#
#---Date:-----------24.11.2017--------------------------------------------------------------------------#
#########################################################################################################

import sys
import random
import string

#	ifInt (bool) - checks if given variable is integer 
def ifInt(variableToCheck) :
    try: 
        int(variableToCheck)
        return True
    except ValueError:
        return False

#	namesGenerator (str) - generates a random ASCII-lettered sequence; size of sequence is 3 < X < 9 
def namesGenerator() :
	randomLetters = ""
	lettersQuantity = random.randint(3,9)	#lettersQuantity - size of sequence
	for x in xrange(1,lettersQuantity):
		randomLetters += random.choice(string.ascii_letters)
	return randomLetters.capitalize()

#	namesGenerator (str) - generates a random sequence of integers; size of sequence is 1 < X < 8
def numbersGenerator() :
	fakeNumber = ""
	for x in xrange(1,8):
		fakeNumber += str(random.randint(0,9))
	return fakeNumber

encodedBase64Photo = "R0lGODlhBQAFAIAAAFyqXP///yH5BAEAAAEALAAAAAAFAAUAAAIEhI+pWAA7" #Base64-encoded GIF photo. Used if user sets True in one of arguments

quantityParametr = 0 #variable to store quantity of contacts, which should be generated
isPhotoParametr = False #variable to store parametr if PHOTO should be added to vCard. 

counter = 1 #defining counter for using in 'while' loop

#	parsing first two given arguments and checking if they can be a parameters for vCard generator 
while (counter < len (sys.argv) <= 3) :
	if (ifInt(sys.argv[counter])) & (quantityParametr == 0) :		
		quantityParametr = abs(int(sys.argv[counter])) #if negative integer was given - absolute value will be taken
		counter +=1	
	else :
		if (str(sys.argv[counter]).lower() == "true") :
			isPhotoParametr = True
			counter +=1
		else :
			counter +=1

#	checking if defaults or user's arguments should be using as parameters for vCard generating   		
if quantityParametr == 0:
	quantityParametr = 10
	print "\n\tCouldn't read quantity parametr... Default parametr {} will be used instead...\n".format(quantityParametr)
if isPhotoParametr == False:
	print "\n\tCouldn't read photo parametr... Default parametr ({}) will be used instead...\n".format(str(isPhotoParametr))

file = open("autoGenerated-{}-contacts.vcf".format(str(quantityParametr)), "w") #creating and opening file

#	generating of vcard and writing data in file
for x in xrange(1,quantityParametr+1):
	file.write("BEGIN:VCARD\n")
	file.write("VERSION:3.0\n")
	file.write("FN:" + namesGenerator() + "," + namesGenerator() + "\n")
	file.write("ORG:Harman\n")
	file.write("TEL;CELL:+48" + numbersGenerator() + str(x) + "\n")
	if isPhotoParametr == True:
		file.write("PHOTO;ENCODING=b;TYPE=GIF:" + encodedBase64Photo + "\n")
	file.write("URL:http://www.harman.com/\n")
	file.write("END:VCARD\n")
	print "\tvCard number {} created successfully...".format(str(x))

file.close() #closing file